/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalho.delivery.presentation.ui;

/**
 *
 * @author erko
 */
public class ItensPedidoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ItensPedidoView.class.getName());

    /**
     * Creates new form ItensView
     */
    public ItensPedidoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPedidoID = new javax.swing.JLabel();
        scrItens = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnRemoverItem = new javax.swing.JButton();
        lblClienteFulano = new javax.swing.JLabel();
        lblTamanhoPizza = new javax.swing.JLabel();
        lblIngrediente = new javax.swing.JLabel();
        cmbIngrediente = new javax.swing.JComboBox<>();
        scrIngredientesPizza = new javax.swing.JScrollPane();
        tblAdicionaisPizza = new javax.swing.JTable();
        btnAddPizzaAoPedido = new javax.swing.JButton();
        btnLimparIngredientes = new javax.swing.JButton();
        lblBebida = new javax.swing.JLabel();
        cmbBebida = new javax.swing.JComboBox<>();
        lblTamanhoBebida = new javax.swing.JLabel();
        cmbTamanhoBebida = new javax.swing.JComboBox<>();
        btnAddBebidaPedido = new javax.swing.JButton();
        btnCalcularTotal = new javax.swing.JButton();
        btnIncluirAdiciona = new javax.swing.JButton();
        radPizzaPortuguesa = new javax.swing.JRadioButton();
        radPizzaCalabresa = new javax.swing.JRadioButton();
        radPizzaQuatroQueijos = new javax.swing.JRadioButton();
        radPizzaModaCasa = new javax.swing.JRadioButton();
        radPizzaFrangoCatupiry = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPedidoID.setText("Pedido ID: #");

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Item", "Descrição", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrItens.setViewportView(tblItens);

        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.addActionListener(this::btnRemoverItemActionPerformed);

        lblClienteFulano.setText("Cliente: Fulano");

        lblTamanhoPizza.setText("Pizza Base:");

        lblIngrediente.setText("Adicional:");

        cmbIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblAdicionaisPizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Adicionais", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrIngredientesPizza.setViewportView(tblAdicionaisPizza);

        btnAddPizzaAoPedido.setText("Adicionar Pizza ao Pedido");

        btnLimparIngredientes.setText("Limpar");

        lblBebida.setText("Bebida");

        cmbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTamanhoBebida.setText("Tamanho");

        cmbTamanhoBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddBebidaPedido.setText("Adicionar Bebida ao Pedido");

        btnCalcularTotal.setText("Calcular Total Pedido");

        btnIncluirAdiciona.setText("Incluir Adicional");

        buttonGroup1.add(radPizzaPortuguesa);
        radPizzaPortuguesa.setText("Portuguesa");

        buttonGroup1.add(radPizzaCalabresa);
        radPizzaCalabresa.setText("Calabresa");

        buttonGroup1.add(radPizzaQuatroQueijos);
        radPizzaQuatroQueijos.setText("Quatro Queijos");

        buttonGroup1.add(radPizzaModaCasa);
        radPizzaModaCasa.setText("Moda da Casa");

        buttonGroup1.add(radPizzaFrangoCatupiry);
        radPizzaFrangoCatupiry.setText("Frango com Catupiry");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPedidoID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClienteFulano, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRemoverItem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCalcularTotal))
                                    .addComponent(scrItens, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIncluirAdiciona)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddPizzaAoPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparIngredientes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radPizzaPortuguesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radPizzaCalabresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radPizzaQuatroQueijos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIngrediente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTamanhoPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radPizzaModaCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radPizzaFrangoCatupiry)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrIngredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamanhoBebida)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblBebida)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAddBebidaPedido))
                            .addComponent(cmbTamanhoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedidoID)
                    .addComponent(lblClienteFulano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanhoPizza)
                    .addComponent(radPizzaModaCasa)
                    .addComponent(radPizzaFrangoCatupiry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPizzaPortuguesa)
                    .addComponent(radPizzaCalabresa)
                    .addComponent(radPizzaQuatroQueijos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediente)
                    .addComponent(cmbIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnIncluirAdiciona)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrIngredientesPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBebida)
                            .addComponent(cmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTamanhoBebida)
                            .addComponent(cmbTamanhoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBebidaPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPizzaAoPedido)
                    .addComponent(btnLimparIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrItens, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverItem)
                    .addComponent(btnCalcularTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ItensPedidoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBebidaPedido;
    private javax.swing.JButton btnAddPizzaAoPedido;
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnIncluirAdiciona;
    private javax.swing.JButton btnLimparIngredientes;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbBebida;
    private javax.swing.JComboBox<String> cmbIngrediente;
    private javax.swing.JComboBox<String> cmbTamanhoBebida;
    private javax.swing.JLabel lblBebida;
    private javax.swing.JLabel lblClienteFulano;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblPedidoID;
    private javax.swing.JLabel lblTamanhoBebida;
    private javax.swing.JLabel lblTamanhoPizza;
    private javax.swing.JRadioButton radPizzaCalabresa;
    private javax.swing.JRadioButton radPizzaFrangoCatupiry;
    private javax.swing.JRadioButton radPizzaModaCasa;
    private javax.swing.JRadioButton radPizzaPortuguesa;
    private javax.swing.JRadioButton radPizzaQuatroQueijos;
    private javax.swing.JScrollPane scrIngredientesPizza;
    private javax.swing.JScrollPane scrItens;
    private javax.swing.JTable tblAdicionaisPizza;
    private javax.swing.JTable tblItens;
    // End of variables declaration//GEN-END:variables
}
